/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SimpleChat': ApiRouteHandler<{ message: string }, ApiResponse<200, { reply: string }> | ApiResponse<400, { error: string }> | ApiResponse<502, { error: string }>, never>
  }
    
}